name: Terraform Dev Deployment

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main      

permissions:
  id-token: write
  contents: read
  
jobs: 
  terraform-init-plan:
    runs-on: self-hosted
    steps: 
      - name: Checkout
        uses: actions/checkout@v5.0.0
    
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 2e5716e1-21ef-403b-8b39-fa79c7ae2f4a
          tenant-id: ba820411-fb17-40b7-aa1e-e6bb2ba7b2da
          subscription-id: c8ae0155-19b9-4306-a16f-ce3e1dab29f4

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: environments/dev 
        
      - name: Terraform Init
        shell: pwsh
        working-directory: environments/dev 
        run: |
          terraform init `
            -backend-config="resource_group_name=${{ secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME }}" `
            -backend-config="storage_account_name=${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }}" `
            -backend-config="container_name=${{ secrets.BACKEND_AZURE_CONTAINER_NAME }}" `
            -backend-config="key=${{ secrets.BACKEND_AZURE_KEY }}"

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: environments/dev     
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
        working-directory: environments/dev 
        
  terraform-apply:    
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    needs: terraform-init-plan
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
    
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
         client-id: dd1efe98-399e-4fb5-b5f4-2d0f0bfd525b
         tenant-id: 90eaef6b-3882-4c51-8467-1155649bc19d
         subscription-id: fbac4321-0f41-46f0-baea-f23a62385eb5 
          
      - name: Terraform Init
        id: init
        run: terraform init -input=false  
        working-directory: ./enviroments/dev

      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
        continue-on-error: true
        working-directory: ./enviroments/dev
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
